spring:
  datasource:
    url: jdbc:postgresql://ec2-52-70-186-184.compute-1.amazonaws.com:5432/dco7daplg7nktl
    username: wyebyevjztpxvg
    password: 612a05327bb0b09dd3a89d4613c1a34ec1618f905663885afd2c7974d559d271
  jpa:
    hibernate:
     ddl-auto: none
    show-sql: true
    properties:
     hibernate:
      format_sql: true
  servlet:     
    multipart:
      max-file-size: 20MB
