spring:
  datasource:
    url: jdbc:mysql://localhost:3306/documents
    username: root
    password: Mundo4278!
  jpa:
    hibernate:
     ddl-auto: none
    show-sql: true
    properties:
     hibernate:
      format_sql: true
  servlet:     
    multipart:
      max-file-size: 20MB
